server:
  port: 8888
  ssl:
    key-store: classpath:jks/DEV/private.jks
    key-store-password: changeit
    key-store-type: JKS
    trust-store: classpath:jks/DEV/public.jks
    trust-store-password: changeit
    trust-store-type: JKS

encrypt:
  key-store:
    location: classpath:jks/DEV/enc_key.jks
    password: changeit
    alias: localhost-ep
    secret: changeit
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        encrypt:
          enabled: true
        git:
          uri: git@github.com:animeshmalik/configrepo.git
          search-paths:
            - DEV/{application}
          ignoreLocalSshSettings: true
          clone-on-start: true
          privateKey: |
            -----BEGIN OPENSSH PRIVATE KEY-----
            some key
            -----END OPENSSH PRIVATE KEY-----